//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CouponCodeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CouponCodeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CouponCodeResources", typeof(CouponCodeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متقدم.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالعربي.
        /// </summary>
        public static string ArabicTitle {
            get {
                return ResourceManager.GetString("ArabicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل العنوان بالعربي.
        /// </summary>
        public static string ArabicTitlePlaceholder {
            get {
                return ResourceManager.GetString("ArabicTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التدقيق.
        /// </summary>
        public static string AuditInfo {
            get {
                return ResourceManager.GetString("AuditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الأساسية.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوبون على الفئة.
        /// </summary>
        public static string CategoryBasedCoupon {
            get {
                return ResourceManager.GetString("CategoryBasedCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم تحويل الأحرف تلقائياً إلى كبيرة.
        /// </summary>
        public static string CodeHint {
            get {
                return ResourceManager.GetString("CodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثال: SAVE20.
        /// </summary>
        public static string CodePlaceholder {
            get {
                return ResourceManager.GetString("CodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوبون مشترك.
        /// </summary>
        public static string CoFundedCoupon {
            get {
                return ResourceManager.GetString("CoFundedCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة مشاركة المنصة في الخصم (الباقي يتحمله البائع).
        /// </summary>
        public static string CoFundingHint {
            get {
                return ResourceManager.GetString("CoFundingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من إيقاف الكوبون؟.
        /// </summary>
        public static string ConfirmDeactivateCoupon {
            get {
                return ResourceManager.GetString("ConfirmDeactivateCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف كود الخصم؟.
        /// </summary>
        public static string ConfirmDeleteCoupon {
            get {
                return ResourceManager.GetString("ConfirmDeleteCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل الكوبون.
        /// </summary>
        public static string CouponActivated {
            get {
                return ResourceManager.GetString("CouponActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تطبيق كود الخصم بنجاح.
        /// </summary>
        public static string CouponAppliedSuccessfully {
            get {
                return ResourceManager.GetString("CouponAppliedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استخدام الكود مسبقاً.
        /// </summary>
        public static string CouponCodeAlreadyUsed {
            get {
                return ResourceManager.GetString("CouponCodeAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود مستخدم بالفعل.
        /// </summary>
        public static string CouponCodeDuplicate {
            get {
                return ResourceManager.GetString("CouponCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم منتهي الصلاحية.
        /// </summary>
        public static string CouponCodeExpired {
            get {
                return ResourceManager.GetString("CouponCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاح للطلب الأول فقط.
        /// </summary>
        public static string CouponCodeFirstOrderOnly {
            get {
                return ResourceManager.GetString("CouponCodeFirstOrderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم غير صحيح.
        /// </summary>
        public static string CouponCodeInvalid {
            get {
                return ResourceManager.GetString("CouponCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب لا يستوفي الحد الأدنى.
        /// </summary>
        public static string CouponCodeMinimumOrderNotMet {
            get {
                return ResourceManager.GetString("CouponCodeMinimumOrderNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير قابل للتطبيق على هذا الطلب.
        /// </summary>
        public static string CouponCodeNotApplicable {
            get {
                return ResourceManager.GetString("CouponCodeNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم لم يبدأ بعد.
        /// </summary>
        public static string CouponCodeNotStarted {
            get {
                return ResourceManager.GetString("CouponCodeNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم مطلوب.
        /// </summary>
        public static string CouponCodeRequired {
            get {
                return ResourceManager.GetString("CouponCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكوادالخصم.
        /// </summary>
        public static string CouponCodes {
            get {
                return ResourceManager.GetString("CouponCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الوصول للحد الأقصى.
        /// </summary>
        public static string CouponCodeUsageLimitReached {
            get {
                return ResourceManager.GetString("CouponCodeUsageLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاوزت الحد الأقصى لاستخدامك.
        /// </summary>
        public static string CouponCodeUserLimitReached {
            get {
                return ResourceManager.GetString("CouponCodeUserLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء كود الخصم بنجاح.
        /// </summary>
        public static string CouponCreatedSuccessfully {
            get {
                return ResourceManager.GetString("CouponCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إيقاف الكوبون.
        /// </summary>
        public static string CouponDeactivated {
            get {
                return ResourceManager.GetString("CouponDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف كود الخصم بنجاح.
        /// </summary>
        public static string CouponDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CouponDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكوبون غير مفعل.
        /// </summary>
        public static string CouponInactive {
            get {
                return ResourceManager.GetString("CouponInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الكوبون.
        /// </summary>
        public static string CouponInfo {
            get {
                return ResourceManager.GetString("CouponInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير قابل للتطبيق على العناصر في السلة.
        /// </summary>
        public static string CouponNotApplicableToCart {
            get {
                return ResourceManager.GetString("CouponNotApplicableToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكوبون غير موجود.
        /// </summary>
        public static string CouponNotFound {
            get {
                return ResourceManager.GetString("CouponNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إزالة كود الخصم بنجاح.
        /// </summary>
        public static string CouponRemovedSuccessfully {
            get {
                return ResourceManager.GetString("CouponRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة التوفير من الكوبون: {0}.
        /// </summary>
        public static string CouponSavingAmount {
            get {
                return ResourceManager.GetString("CouponSavingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نطاق الكوبون.
        /// </summary>
        public static string CouponScope {
            get {
                return ResourceManager.GetString("CouponScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث كود الخصم بنجاح.
        /// </summary>
        public static string CouponUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("CouponUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام الكوبون.
        /// </summary>
        public static string CouponUsage {
            get {
                return ResourceManager.GetString("CouponUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قارب الكوبون على الوصول لحد الاستخدام.
        /// </summary>
        public static string CouponUsageLimitWarning {
            get {
                return ResourceManager.GetString("CouponUsageLimitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحقق من الكوبون بنجاح.
        /// </summary>
        public static string CouponValidated {
            get {
                return ResourceManager.GetString("CouponValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحية الكوبون.
        /// </summary>
        public static string CouponValidity {
            get {
                return ResourceManager.GetString("CouponValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ينتهي صلاحية الكوبون قريباً.
        /// </summary>
        public static string CouponWillExpireSoon {
            get {
                return ResourceManager.GetString("CouponWillExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستخدام الحالي.
        /// </summary>
        public static string CurrentUsage {
            get {
                return ResourceManager.GetString("CurrentUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل وصف الكوبون (اختياري).
        /// </summary>
        public static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تطبيق الخصم.
        /// </summary>
        public static string DiscountApplied {
            get {
                return ResourceManager.GetString("DiscountApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الخصم.
        /// </summary>
        public static string DiscountInfo {
            get {
                return ResourceManager.GetString("DiscountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات الخصم.
        /// </summary>
        public static string DiscountSettings {
            get {
                return ResourceManager.GetString("DiscountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الخصم.
        /// </summary>
        public static string DiscountType {
            get {
                return ResourceManager.GetString("DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الخصم يجب أن تكون موجبة.
        /// </summary>
        public static string DiscountValueMustBePositive {
            get {
                return ResourceManager.GetString("DiscountValueMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الخصم مطلوبة.
        /// </summary>
        public static string DiscountValueRequired {
            get {
                return ResourceManager.GetString("DiscountValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالإنجليزي.
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter English Title.
        /// </summary>
        public static string EnglishTitlePlaceholder {
            get {
                return ResourceManager.GetString("EnglishTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكوبون متاح فقط للعملاء الجدد في أول طلب.
        /// </summary>
        public static string FirstOrderHint {
            get {
                return ResourceManager.GetString("FirstOrderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للطلب الأول فقط.
        /// </summary>
        public static string FirstOrderOnly {
            get {
                return ResourceManager.GetString("FirstOrderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ثابت.
        /// </summary>
        public static string FixedAmountDiscount {
            get {
                return ResourceManager.GetString("FixedAmountDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل المبلغ الثابت بالريال.
        /// </summary>
        public static string FixedAmountHint {
            get {
                return ResourceManager.GetString("FixedAmountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوبون عام.
        /// </summary>
        public static string GeneralCoupon {
            get {
                return ResourceManager.GetString("GeneralCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير نشط.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود خصم غير صالح.
        /// </summary>
        public static string InvalidCouponCode {
            get {
                return ResourceManager.GetString("InvalidCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الكوبون غير صحيح.
        /// </summary>
        public static string InvalidCouponType {
            get {
                return ResourceManager.GetString("InvalidCouponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للطلب الأول فقط.
        /// </summary>
        public static string IsFirstOrderOnly {
            get {
                return ResourceManager.GetString("IsFirstOrderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوبون على المنتجات.
        /// </summary>
        public static string ItemBasedCoupon {
            get {
                return ResourceManager.GetString("ItemBasedCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود والقواعد.
        /// </summary>
        public static string LimitsAndRules {
            get {
                return ResourceManager.GetString("LimitsAndRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جارِ التحميل....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى للخصم.
        /// </summary>
        public static string MaxDiscountAmount {
            get {
                return ResourceManager.GetString("MaxDiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى للخصم عند استخدام النسبة المئوية.
        /// </summary>
        public static string MaxDiscountHint {
            get {
                return ResourceManager.GetString("MaxDiscountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأدنى للطلب.
        /// </summary>
        public static string MinimumOrderAmount {
            get {
                return ResourceManager.GetString("MinimumOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقل قيمة للطلب لتطبيق الكوبون.
        /// </summary>
        public static string MinOrderHint {
            get {
                return ResourceManager.GetString("MinOrderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للعملاء الجدد فقط.
        /// </summary>
        public static string NewUserOnlyCoupon {
            get {
                return ResourceManager.GetString("NewUserOnlyCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختياري.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة مئوية.
        /// </summary>
        public static string PercentageDiscount {
            get {
                return ResourceManager.GetString("PercentageDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل نسبة من 0 إلى 100.
        /// </summary>
        public static string PercentageHint {
            get {
                return ResourceManager.GetString("PercentageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة المئوية يجب أن تكون بين 0 و 100.
        /// </summary>
        public static string PercentageValueInvalid {
            get {
                return ResourceManager.GetString("PercentageValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المرات التي يمكن للعميل استخدام الكوبون.
        /// </summary>
        public static string PerUserHint {
            get {
                return ResourceManager.GetString("PerUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حد الاستخدام لكل مستخدم.
        /// </summary>
        public static string PerUserLimit {
            get {
                return ResourceManager.GetString("PerUserLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة المنصة.
        /// </summary>
        public static string PlatformShare {
            get {
                return ResourceManager.GetString("PlatformShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة مشاركة المنصة.
        /// </summary>
        public static string PlatformSharePercentage {
            get {
                return ResourceManager.GetString("PlatformSharePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال كود الخصم.
        /// </summary>
        public static string PleaseEnterCouponCode {
            get {
                return ResourceManager.GetString("PleaseEnterCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم.
        /// </summary>
        public static string PromoCode {
            get {
                return ResourceManager.GetString("PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشاركون في البرومو كود.
        /// </summary>
        public static string PromoCodeParticipations {
            get {
                return ResourceManager.GetString("PromoCodeParticipations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكواد الخصم.
        /// </summary>
        public static string PromoCodes {
            get {
                return ResourceManager.GetString("PromoCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع كود الخصم.
        /// </summary>
        public static string PromoCodeType {
            get {
                return ResourceManager.GetString("PromoCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتبقي.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستخدام المتبقي.
        /// </summary>
        public static string RemainingUsage {
            get {
                return ResourceManager.GetString("RemainingUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جارِ الحفظ....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد العناصر المؤهلة للخصم.
        /// </summary>
        public static string ScopeItemsRequired {
            get {
                return ResourceManager.GetString("ScopeItemsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قواعد خاصة.
        /// </summary>
        public static string SpecialRules {
            get {
                return ResourceManager.GetString("SpecialRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء يجب أن يكون قبل الانتهاء.
        /// </summary>
        public static string StartDateMustBeBeforeEndDate {
            get {
                return ResourceManager.GetString("StartDateMustBeBeforeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتركه فارغاً للاستخدام غير المحدود.
        /// </summary>
        public static string TotalUsageHint {
            get {
                return ResourceManager.GetString("TotalUsageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي حد الاستخدام.
        /// </summary>
        public static string TotalUsageLimit {
            get {
                return ResourceManager.GetString("TotalUsageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الاستخدام.
        /// </summary>
        public static string TotalUsed {
            get {
                return ResourceManager.GetString("TotalUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام غير محدود.
        /// </summary>
        public static string UnlimitedUsage {
            get {
                return ResourceManager.GetString("UnlimitedUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستخدام.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد مرات الاستخدام.
        /// </summary>
        public static string UsageCount {
            get {
                return ResourceManager.GetString("UsageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حد الإستخدام.
        /// </summary>
        public static string UsageLimit {
            get {
                return ResourceManager.GetString("UsageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حد الاستخدام لكل مستخدم.
        /// </summary>
        public static string UsageLimitPerUser {
            get {
                return ResourceManager.GetString("UsageLimitPerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدود الاستخدام.
        /// </summary>
        public static string UsageLimits {
            get {
                return ResourceManager.GetString("UsageLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحصائيات الاستخدام.
        /// </summary>
        public static string UsageStatistics {
            get {
                return ResourceManager.GetString("UsageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صالح من.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فترة الصلاحية.
        /// </summary>
        public static string ValidityPeriod {
            get {
                return ResourceManager.GetString("ValidityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صالح حتى.
        /// </summary>
        public static string ValidUntil {
            get {
                return ResourceManager.GetString("ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البائع.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوبون على البائع.
        /// </summary>
        public static string VendorBasedCoupon {
            get {
                return ResourceManager.GetString("VendorBasedCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد البائع للكوبونات المشتركة.
        /// </summary>
        public static string VendorRequiredForCoFunded {
            get {
                return ResourceManager.GetString("VendorRequiredForCoFunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وفرت.
        /// </summary>
        public static string YouSaved {
            get {
                return ResourceManager.GetString("YouSaved", resourceCulture);
            }
        }
    }
}
