//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CurrencyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CurrencyResources", typeof(CurrencyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالعربية.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أساسي.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر العملة الأساسية دائماً 1.0.
        /// </summary>
        public static string BaseCurrencyRateAlwaysOne {
            get {
                return ResourceManager.GetString("BaseCurrencyRateAlwaysOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث العملة الأساسية بنجاح.
        /// </summary>
        public static string BaseCurrencyUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("BaseCurrencyUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف العملة الأساسية. يرجى تعيين عملة أخرى كأساسية أولاً..
        /// </summary>
        public static string CannotDeleteBaseCurrency {
            get {
                return ResourceManager.GetString("CannotDeleteBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الدولة.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز العملة (ISO).
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملات.
        /// </summary>
        public static string CurrencyManagement {
            get {
                return ResourceManager.GetString("CurrencyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز العملة.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالإنجليزية.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الصرف.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث أسعار الصرف بنجاح.
        /// </summary>
        public static string ExchangeRatesUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ExchangeRatesUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تعيين العملة الأساسية.
        /// </summary>
        public static string FailedToSetBaseCurrency {
            get {
                return ResourceManager.GetString("FailedToSetBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تحديث أسعار الصرف.
        /// </summary>
        public static string FailedToUpdateExchangeRates {
            get {
                return ResourceManager.GetString("FailedToUpdateExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير نشط.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر نسبة للعملة الأساسية.
        /// </summary>
        public static string RateRelativeToBaseCurrency {
            get {
                return ResourceManager.GetString("RateRelativeToBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين كأساسي.
        /// </summary>
        public static string SetAsBase {
            get {
                return ResourceManager.GetString("SetAsBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين العملة الأساسية.
        /// </summary>
        public static string SetBaseCurrency {
            get {
                return ResourceManager.GetString("SetBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد بالتأكيد تعيين {0} كعملة أساسية؟ سيتم تحديث جميع أسعار الصرف..
        /// </summary>
        public static string SetBaseCurrencyConfirmation {
            get {
                return ResourceManager.GetString("SetBaseCurrencyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عملة ISO من 3 أحرف.
        /// </summary>
        public static string ThreeLetterISOCurrencyCode {
            get {
                return ResourceManager.GetString("ThreeLetterISOCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز دولة من حرفين (اختياري).
        /// </summary>
        public static string TwoLetterCountryCode {
            get {
                return ResourceManager.GetString("TwoLetterCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث الأسعار.
        /// </summary>
        public static string UpdateRates {
            get {
                return ResourceManager.GetString("UpdateRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم، عين كأساسي.
        /// </summary>
        public static string YesSetAsBase {
            get {
                return ResourceManager.GetString("YesSetAsBase", resourceCulture);
            }
        }
    }
}
