//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ECommerceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ECommerceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ECommerceResources", typeof(ECommerceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقبول.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحساب.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الحسابات .
        /// </summary>
        public static string AccountTypes {
            get {
                return ResourceManager.GetString("AccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات المفعلّة.
        /// </summary>
        public static string ActivatedAccounts {
            get {
                return ResourceManager.GetString("ActivatedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجار النشطون.
        /// </summary>
        public static string ActiveVendors {
            get {
                return ResourceManager.GetString("ActiveVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف خاصية.
        /// </summary>
        public static string AddAttribute {
            get {
                return ResourceManager.GetString("AddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة حقل.
        /// </summary>
        public static string AddField {
            get {
                return ResourceManager.GetString("AddField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرق تواصل إضافية.
        /// </summary>
        public static string AdditionalContactMethods {
            get {
                return ResourceManager.GetString("AdditionalContactMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف قيم متعددة لمجموعات التسعير.
        /// </summary>
        public static string AddMultipleValuesForPricing {
            get {
                return ResourceManager.GetString("AddMultipleValuesForPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة خيار.
        /// </summary>
        public static string AddOption {
            get {
                return ResourceManager.GetString("AddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسؤول.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المسؤول.
        /// </summary>
        public static string AdministratorName {
            get {
                return ResourceManager.GetString("AdministratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسؤولون.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم الذكية.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلان.
        /// </summary>
        public static string Advert {
            get {
                return ResourceManager.GetString("Advert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالات الإعلان.
        /// </summary>
        public static string AdvertiseConditions {
            get {
                return ResourceManager.GetString("AdvertiseConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحكم في الإعلانات.
        /// </summary>
        public static string AdvertiseControl {
            get {
                return ResourceManager.GetString("AdvertiseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مُعلن.
        /// </summary>
        public static string Advertiser {
            get {
                return ResourceManager.GetString("Advertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف المعلن.
        /// </summary>
        public static string AdvertiserProfile {
            get {
                return ResourceManager.GetString("AdvertiserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المُعلنين.
        /// </summary>
        public static string Advertisers {
            get {
                return ResourceManager.GetString("Advertisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المعلن.
        /// </summary>
        public static string AdvertiserType {
            get {
                return ResourceManager.GetString("AdvertiserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        public static string Adverts {
            get {
                return ResourceManager.GetString("Adverts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهدات الإعلان.
        /// </summary>
        public static string AdvertViews {
            get {
                return ResourceManager.GetString("AdvertViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يؤثر على السعر.
        /// </summary>
        public static string AffectsPricing {
            get {
                return ResourceManager.GetString("AffectsPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاصية &quot;تؤثر على التسعير&quot; متوفرة فقط للسمات من نوع القائمة.
        /// </summary>
        public static string AffectsPricingListTypeOnly {
            get {
                return ResourceManager.GetString("AffectsPricingListTypeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع أنواع المعلنين.
        /// </summary>
        public static string AllAdvertiserTypes {
            get {
                return ResourceManager.GetString("AllAdvertiserTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقول المميزة بـ * مطلوبة.
        /// </summary>
        public static string AllFieldsMarkedRequired {
            get {
                return ResourceManager.GetString("AllFieldsMarkedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتمد.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التخصص باللغة العربية.
        /// </summary>
        public static string ArabicSpecializationName {
            get {
                return ResourceManager.GetString("ArabicSpecializationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخاصية.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعات الخصائص.
        /// </summary>
        public static string AttributeCombinations {
            get {
                return ResourceManager.GetString("AttributeCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصائص.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيم الخصائص.
        /// </summary>
        public static string AttributeValues {
            get {
                return ResourceManager.GetString("AttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق تلقائياً.
        /// </summary>
        public static string AutoLocked {
            get {
                return ResourceManager.GetString("AutoLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية المتاحة.
        /// </summary>
        public static string AvailableQuantity {
            get {
                return ResourceManager.GetString("AvailableQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط التقييم.
        /// </summary>
        public static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة البانر.
        /// </summary>
        public static string BannerDuration {
            get {
                return ResourceManager.GetString("BannerDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة البانر.
        /// </summary>
        public static string BannerDuration_Duplicate_1_ {
            get {
                return ResourceManager.GetString("BannerDuration_Duplicate[1]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر الأساسي.
        /// </summary>
        public static string BasePrice {
            get {
                return ResourceManager.GetString("BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكافأة.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكافأة / الشهر.
        /// </summary>
        public static string BonusPerMonth {
            get {
                return ResourceManager.GetString("BonusPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلنون التجاريون.
        /// </summary>
        public static string BusinessAdvertisers {
            get {
                return ResourceManager.GetString("BusinessAdvertisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العمل.
        /// </summary>
        public static string BusinessInformation {
            get {
                return ResourceManager.GetString("BusinessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف التجاري.
        /// </summary>
        public static string BusinessProfile {
            get {
                return ResourceManager.GetString("BusinessProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإلغاء.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الكتالوج.
        /// </summary>
        public static string CatalogManagement {
            get {
                return ResourceManager.GetString("CatalogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئات.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصائص الفئة.
        /// </summary>
        public static string CategoryAttributes {
            get {
                return ResourceManager.GetString("CategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الفئة.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة الرئيسية.
        /// </summary>
        public static string CategoryParent {
            get {
                return ResourceManager.GetString("CategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانة اختيار.
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدن.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدينه.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخيارات.
        /// </summary>
        public static string Combinations {
            get {
                return ResourceManager.GetString("Combinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قريباً.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل التجاري.
        /// </summary>
        public static string CommercialRegister {
            get {
                return ResourceManager.GetString("CommercialRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة العمولة .
        /// </summary>
        public static string CommissionRate {
            get {
                return ResourceManager.GetString("CommissionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاوردارات المكتمله.
        /// </summary>
        public static string CompletedOrders {
            get {
                return ResourceManager.GetString("CompletedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحالة.
        /// </summary>
        public static string ConditionName {
            get {
                return ResourceManager.GetString("ConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بتكوين الخصائص لهذا المنتج.
        /// </summary>
        public static string ConfigureAttributes {
            get {
                return ResourceManager.GetString("ConfigureAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المسؤول.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معامل التحويل.
        /// </summary>
        public static string ConversionFactor {
            get {
                return ResourceManager.GetString("ConversionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات المحول منها.
        /// </summary>
        public static string ConvertFromUnits {
            get {
                return ResourceManager.GetString("ConvertFromUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات المحول إليها.
        /// </summary>
        public static string ConvertToUnits {
            get {
                return ResourceManager.GetString("ConvertToUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدول.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملات.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمله.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العملة.
        /// </summary>
        public static string CurrencyInformation {
            get {
                return ResourceManager.GetString("CurrencyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الحالي.
        /// </summary>
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العميل.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( {0} ) : ( {1} ) ( {2} أيام ).
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم عشري.
        /// </summary>
        public static string DecimalNumber {
            get {
                return ResourceManager.GetString("DecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم استخدام التسعير الافتراضي إذا لم يتم تعيين أسعار للخيارات..
        /// </summary>
        public static string DefaultPricingNote {
            get {
                return ResourceManager.GetString("DefaultPricingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احذف صف المثال قبل الاستيراد.
        /// </summary>
        public static string DeleteExampleRow {
            get {
                return ResourceManager.GetString("DeleteExampleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسليم.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات البيع المباشر.
        /// </summary>
        public static string DirectSaleOrders {
            get {
                return ResourceManager.GetString("DirectSaleOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب العرض.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب العرض.
        /// </summary>
        public static string DisplayOrder_Duplicate_1_ {
            get {
                return ResourceManager.GetString("DisplayOrder_Duplicate[1]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل قالب فارغ.
        /// </summary>
        public static string DownloadEmptyTemplate {
            get {
                return ResourceManager.GetString("DownloadEmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل القالب مع البيانات المرجعية.
        /// </summary>
        public static string DownloadTemplateWithData {
            get {
                return ResourceManager.GetString("DownloadTemplateWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيميل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القالب الفارغ.
        /// </summary>
        public static string EmptyTemplate {
            get {
                return ResourceManager.GetString("EmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يحتوي فقط على ورقة المنتجات والتعليمات (بدون بيانات مرجعية).
        /// </summary>
        public static string EmptyTemplateDescription {
            get {
                return ResourceManager.GetString("EmptyTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفائدة بالإنجليزية.
        /// </summary>
        public static string EnglishBenefit {
            get {
                return ResourceManager.GetString("EnglishBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التخصص باللغة الإنجليزية.
        /// </summary>
        public static string EnglishSpecializationName {
            get {
                return ResourceManager.GetString("EnglishSpecializationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أيام التسليم المقدرة.
        /// </summary>
        public static string EstimatedDeliveryDays {
            get {
                return ResourceManager.GetString("EstimatedDeliveryDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف Excel.
        /// </summary>
        public static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد التسليم المتوقع.
        /// </summary>
        public static string ExpectedDelivery {
            get {
                return ResourceManager.GetString("ExpectedDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتهي.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء الرمز..
        /// </summary>
        public static string FailedToGenerateToken {
            get {
                return ResourceManager.GetString("FailedToGenerateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلن مميز.
        /// </summary>
        public static string FeaturedAdvertiser {
            get {
                return ResourceManager.GetString("FeaturedAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلنون المميزون.
        /// </summary>
        public static string FeaturedAdvertisers {
            get {
                return ResourceManager.GetString("FeaturedAdvertisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحقل.
        /// </summary>
        public static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لكل أسبوع.
        /// </summary>
        public static string ForEveryWeek {
            get {
                return ResourceManager.GetString("ForEveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شحن مجاني.
        /// </summary>
        public static string FreeShipping {
            get {
                return ResourceManager.GetString("FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة المحول منها .
        /// </summary>
        public static string FromUnit {
            get {
                return ResourceManager.GetString("FromUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الهوية (خلف).
        /// </summary>
        public static string IdentificationImageBack {
            get {
                return ResourceManager.GetString("IdentificationImageBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الهوية (أمام).
        /// </summary>
        public static string IdentificationImageFront {
            get {
                return ResourceManager.GetString("IdentificationImageFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الهوية.
        /// </summary>
        public static string IdentificationInformation {
            get {
                return ResourceManager.GetString("IdentificationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IdentificationNumber {
            get {
                return ResourceManager.GetString("IdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الهوية.
        /// </summary>
        public static string IdentificationType {
            get {
                return ResourceManager.GetString("IdentificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استيراد المنتجات.
        /// </summary>
        public static string ImportProducts {
            get {
                return ResourceManager.GetString("ImportProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير نشط.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد التنفيذ.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوفر.
        /// </summary>
        public static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم صحيح.
        /// </summary>
        public static string IntegerNumber {
            get {
                return ResourceManager.GetString("IntegerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صالحة..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخزون.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يؤثر على السعر.
        /// </summary>
        public static string IsAffectPrice {
            get {
                return ResourceManager.GetString("IsAffectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلن مميز.
        /// </summary>
        public static string IsFeaturedAdvertiser {
            get {
                return ResourceManager.GetString("IsFeaturedAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمن التصنيف المميز.
        /// </summary>
        public static string IsFeaturedCategory {
            get {
                return ResourceManager.GetString("IsFeaturedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهائي.
        /// </summary>
        public static string IsFinal {
            get {
                return ResourceManager.GetString("IsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمن الصفحة الرئيسية.
        /// </summary>
        public static string IsHomeCategory {
            get {
                return ResourceManager.GetString("IsHomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمن القائمة الرئيسية.
        /// </summary>
        public static string IsMainCategory {
            get {
                return ResourceManager.GetString("IsMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحقل بنطاق.
        /// </summary>
        public static string IsRangeFieldType {
            get {
                return ResourceManager.GetString("IsRangeFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل مسجل عقارياً.
        /// </summary>
        public static string IsRealEstateRegistered {
            get {
                return ResourceManager.GetString("IsRealEstateRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلن موثق.
        /// </summary>
        public static string IsVerifiedAdvertiser {
            get {
                return ResourceManager.GetString("IsVerifiedAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمات العنصر.
        /// </summary>
        public static string ItemAttributes {
            get {
                return ResourceManager.GetString("ItemAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العنصر.
        /// </summary>
        public static string ItemCondition {
            get {
                return ResourceManager.GetString("ItemCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالات العنصر.
        /// </summary>
        public static string ItemConditions {
            get {
                return ResourceManager.GetString("ItemConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملة العنصر.
        /// </summary>
        public static string ItemCurrency {
            get {
                return ResourceManager.GetString("ItemCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنصر متاح.
        /// </summary>
        public static string ItemsAvailable {
            get {
                return ResourceManager.GetString("ItemsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع القائمة.
        /// </summary>
        public static string ListType {
            get {
                return ResourceManager.GetString("ListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض القائمة.
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عتبة نقص المخزون.
        /// </summary>
        public static string LowStockThreshold {
            get {
                return ResourceManager.GetString("LowStockThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللوجستيات والشحن.
        /// </summary>
        public static string LogisticsAndShipping {
            get {
                return ResourceManager.GetString("LogisticsAndShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير: الكمية منخفضة.
        /// </summary>
        public static string LowStockWarning {
            get {
                return ResourceManager.GetString("LowStockWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البانر الرئيسي.
        /// </summary>
        public static string MainBanner {
            get {
                return ResourceManager.GetString("MainBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البانرات الرئيسية.
        /// </summary>
        public static string MainBanners {
            get {
                return ResourceManager.GetString("MainBanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة الرئيسية.
        /// </summary>
        public static string MainCurrency {
            get {
                return ResourceManager.GetString("MainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة حالة الحساب.
        /// </summary>
        public static string ManageUserStatus {
            get {
                return ResourceManager.GetString("ManageUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة تفاصيل البائع وحالته.
        /// </summary>
        public static string ManageVendorDetailsDescription {
            get {
                return ResourceManager.GetString("ManageVendorDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة حالة البائع.
        /// </summary>
        public static string ManageVendorStatus {
            get {
                return ResourceManager.GetString("ManageVendorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسوّق.
        /// </summary>
        public static string Marketer {
            get {
                return ResourceManager.GetString("Marketer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسوّقون.
        /// </summary>
        public static string Marketers {
            get {
                return ResourceManager.GetString("Marketers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر الأقصى.
        /// </summary>
        public static string MaximumPrice {
            get {
                return ResourceManager.GetString("MaximumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطول الأقصى.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى للطلب.
        /// </summary>
        public static string MaxOrderQuantity {
            get {
                return ResourceManager.GetString("MaxOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر الأدنى.
        /// </summary>
        public static string MinimumPrice {
            get {
                return ResourceManager.GetString("MinimumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأدنى للطلب.
        /// </summary>
        public static string MinOrderQuantity {
            get {
                return ResourceManager.GetString("MinOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل إلى تم التسليم.
        /// </summary>
        public static string MoveToDelivered {
            get {
                return ResourceManager.GetString("MoveToDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل إلى قيد المعالجة.
        /// </summary>
        public static string MoveToInProgress {
            get {
                return ResourceManager.GetString("MoveToInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل إلى الشحن.
        /// </summary>
        public static string MoveToShipping {
            get {
                return ResourceManager.GetString("MoveToShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة اختيار متعددة.
        /// </summary>
        public static string MultiSelectList {
            get {
                return ResourceManager.GetString("MultiSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب جديد.
        /// </summary>
        public static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات إضافة منتجات جديدة.
        /// </summary>
        public static string NewProductRequests {
            get {
                return ResourceManager.GetString("NewProductRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد خيارات.
        /// </summary>
        public static string No_Options_Configured {
            get {
                return ResourceManager.GetString("No Options Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد خصائص متاحة.
        /// </summary>
        public static string NoAttributes {
            get {
                return ResourceManager.GetString("NoAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إضافة أي خصائص بعد.
        /// </summary>
        public static string NoAttributesAdded {
            get {
                return ResourceManager.GetString("NoAttributesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تكوين خيارات لهذه الخاصية.
        /// </summary>
        public static string NoOptionsConfigured {
            get {
                return ResourceManager.GetString("NoOptionsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد طرق دفع متاحة حالياً. .
        /// </summary>
        public static string NoPaymentMethodsAvailable {
            get {
                return ResourceManager.GetString("NoPaymentMethodsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد تقييم.
        /// </summary>
        public static string NoRating {
            get {
                return ResourceManager.GetString("NoRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد طرق سحب متاحه.
        /// </summary>
        public static string NoWithdrawalMethodsAvailable {
            get {
                return ResourceManager.GetString("NoWithdrawalMethodsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الطلب.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكلفة إضافية للطلب.
        /// </summary>
        public static string OrderExtraCost {
            get {
                return ResourceManager.GetString("OrderExtraCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الطلبات.
        /// </summary>
        public static string OrderManagement {
            get {
                return ResourceManager.GetString("OrderManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب قبول الطلب أولاً..
        /// </summary>
        public static string OrderMustBeAccepted {
            get {
                return ResourceManager.GetString("OrderMustBeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون الطلب قيد التنفيذ أولاً..
        /// </summary>
        public static string OrderMustBeInProgress {
            get {
                return ResourceManager.GetString("OrderMustBeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الطلب.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزيع حالات الطلب.
        /// </summary>
        public static string OrderStatusDistribution {
            get {
                return ResourceManager.GetString("OrderStatusDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة ضريبة الطلب.
        /// </summary>
        public static string OrderTaxAmount {
            get {
                return ResourceManager.GetString("OrderTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متوفر في المخزون.
        /// </summary>
        public static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدفوع.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الوالد.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل ومراجعة البيانات.
        /// </summary>
        public static string ParseAndReviewData {
            get {
                return ResourceManager.GetString("ParseAndReviewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة الدفع.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقول طريقة الدفع.
        /// </summary>
        public static string PaymentMethodFields {
            get {
                return ResourceManager.GetString("PaymentMethodFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرق الدفع.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الدفع.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات المعلقة.
        /// </summary>
        public static string PendingOrders {
            get {
                return ResourceManager.GetString("PendingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات المعلقة.
        /// </summary>
        public static string PendingRequests {
            get {
                return ResourceManager.GetString("PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل سعر المنتج.
        /// </summary>
        public static string PricePlaceHolder {
            get {
                return ResourceManager.GetString("PricePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر مطلوب.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التسعير.
        /// </summary>
        public static string PricingInformation {
            get {
                return ResourceManager.GetString("PricingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام التسعير.
        /// </summary>
        public static string PricingSystem {
            get {
                return ResourceManager.GetString("PricingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام التسعير مطلوب.
        /// </summary>
        public static string PricingSystemRequired {
            get {
                return ResourceManager.GetString("PricingSystemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتج.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المنتج بالعربي.
        /// </summary>
        public static string ProductNameAr {
            get {
                return ResourceManager.GetString("ProductNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المنتج بالانجليزي.
        /// </summary>
        public static string ProductNameEn {
            get {
                return ResourceManager.GetString("ProductNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسويق المنتجات.
        /// </summary>
        public static string ProductsMarketing {
            get {
                return ResourceManager.GetString("ProductsMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكواد الخصم.
        /// </summary>
        public static string PromoCodes {
            get {
                return ResourceManager.GetString("PromoCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكميه.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل الكمية المتاحة.
        /// </summary>
        public static string QuantityPlaceHolder {
            get {
                return ResourceManager.GetString("QuantityPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدى.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرتبة.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرتب.
        /// </summary>
        public static string Ranks {
            get {
                return ResourceManager.GetString("Ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطول الموصى به: {0}-{1} حرفًا. الحالي.
        /// </summary>
        public static string RecommendedLengthRangeShort {
            get {
                return ResourceManager.GetString("RecommendedLengthRangeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسترجاعات.
        /// </summary>
        public static string Refunds {
            get {
                return ResourceManager.GetString("Refunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الاسترجاع.
        /// </summary>
        public static string RefundStatus {
            get {
                return ResourceManager.GetString("RefundStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        public static string Refused {
            get {
                return ResourceManager.GetString("Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التسجيل.
        /// </summary>
        public static string RegistrationInfo {
            get {
                return ResourceManager.GetString("RegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلن عادي.
        /// </summary>
        public static string RegularAdvertiser {
            get {
                return ResourceManager.GetString("RegularAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلنون العاديون.
        /// </summary>
        public static string RegularAdvertisers {
            get {
                return ResourceManager.GetString("RegularAdvertisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقيد.
        /// </summary>
        public static string Restricted {
            get {
                return ResourceManager.GetString("Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإرجاع.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيرادات.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييمات.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة الجذرية.
        /// </summary>
        public static string RootCategory {
            get {
                return ResourceManager.GetString("RootCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيعات.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر البيع.
        /// </summary>
        public static string SalesPrice {
            get {
                return ResourceManager.GetString("SalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الفئة التي تريد استيراد المنتجات إليها.
        /// </summary>
        public static string SelectCategoryInstructions {
            get {
                return ResourceManager.GetString("SelectCategoryInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة المختارة.
        /// </summary>
        public static string SelectedCategory {
            get {
                return ResourceManager.GetString("SelectedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر من القائمة المنسدلة للفئة والعلامة التجارية والوحدة.
        /// </summary>
        public static string SelectFromDropdown {
            get {
                return ResourceManager.GetString("SelectFromDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى اختيار شركة الشحن..
        /// </summary>
        public static string SelectShippingCompany {
            get {
                return ResourceManager.GetString("SelectShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى اختيار تاريخ تسليم صالح..
        /// </summary>
        public static string SelectValidDeliveryDate {
            get {
                return ResourceManager.GetString("SelectValidDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات البائع.
        /// </summary>
        public static string SellerInformation {
            get {
                return ResourceManager.GetString("SellerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين التسعير الافتراضي.
        /// </summary>
        public static string SetDefaultPricing {
            get {
                return ResourceManager.GetString("SetDefaultPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الشحن.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسوم الشحن.
        /// </summary>
        public static string ShippingAmount {
            get {
                return ResourceManager.GetString("ShippingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركات الشحن.
        /// </summary>
        public static string ShippingCompanies {
            get {
                return ResourceManager.GetString("ShippingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة الشحن.
        /// </summary>
        public static string ShippingCompany {
            get {
                return ResourceManager.GetString("ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف قصير.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز المنتج (SKU).
        /// </summary>
        public static string SKU {
            get {
                return ResourceManager.GetString("SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة السلايدر.
        /// </summary>
        public static string SliderImage {
            get {
                return ResourceManager.GetString("SliderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان السلايدر.
        /// </summary>
        public static string SliderTitle {
            get {
                return ResourceManager.GetString("SliderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مباع.
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التخصص.
        /// </summary>
        public static string SpecializationName {
            get {
                return ResourceManager.GetString("SpecializationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصصات.
        /// </summary>
        public static string Specializations {
            get {
                return ResourceManager.GetString("Specializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يبدأ من.
        /// </summary>
        public static string StartBy {
            get {
                return ResourceManager.GetString("StartBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الولاية.
        /// </summary>
        public static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظات.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة 1: اختيار الفئة.
        /// </summary>
        public static string Step1SelectCategory {
            get {
                return ResourceManager.GetString("Step1SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة 2: رفع ملف Excel.
        /// </summary>
        public static string Step2UploadFile {
            get {
                return ResourceManager.GetString("Step2UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدة حفظ المخزون (SKU).
        /// </summary>
        public static string StockKeepingUnit {
            get {
                return ResourceManager.GetString("StockKeepingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاله المخزون.
        /// </summary>
        public static string StockStatus {
            get {
                return ResourceManager.GetString("StockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المتجر.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجمالي الفرعي.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسليم بنجاح.
        /// </summary>
        public static string SuccessfullyDelivered {
            get {
                return ResourceManager.GetString("SuccessfullyDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقوف.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة المحول إليها .
        /// </summary>
        public static string TargetUnit {
            get {
                return ResourceManager.GetString("TargetUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الضريبي.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يحتوي على أوراق مرجعية للفئات والعلامات التجارية والوحدات وخيارات الخصائص.
        /// </summary>
        public static string TemplateWithDataDescription {
            get {
                return ResourceManager.GetString("TemplateWithDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القالب مع البيانات المرجعية.
        /// </summary>
        public static string TemplateWithReferenceData {
            get {
                return ResourceManager.GetString("TemplateWithReferenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور مصغره.
        /// </summary>
        public static string ThumbnailImage {
            get {
                return ResourceManager.GetString("ThumbnailImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل التجار أداءً.
        /// </summary>
        public static string TopPerformingVendors {
            get {
                return ResourceManager.GetString("TopPerformingVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات الأكثر مبيعًا.
        /// </summary>
        public static string TopSellingProducts {
            get {
                return ResourceManager.GetString("TopSellingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجمالي.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الإعلانات.
        /// </summary>
        public static string TotalAdverts {
            get {
                return ResourceManager.GetString("TotalAdverts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الطلبات.
        /// </summary>
        public static string TotalOrders {
            get {
                return ResourceManager.GetString("TotalOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي عدد الطلبات.
        /// </summary>
        public static string TotalOrdersCount {
            get {
                return ResourceManager.GetString("TotalOrdersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي المنتجات.
        /// </summary>
        public static string TotalProducts {
            get {
                return ResourceManager.GetString("TotalProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الإيرادات.
        /// </summary>
        public static string TotalRevenue {
            get {
                return ResourceManager.GetString("TotalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الشجرة.
        /// </summary>
        public static string TreeView {
            get {
                return ResourceManager.GetString("TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد المراجعة.
        /// </summary>
        public static string UnderReview {
            get {
                return ResourceManager.GetString("UnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الوحدة.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارفع ملف Excel المملوء ببيانات المنتجات. تأكد من ملء جميع الحقول المطلوبة بشكل صحيح..
        /// </summary>
        public static string UploadFileInstructions {
            get {
                return ResourceManager.GetString("UploadFileInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الحساب.
        /// </summary>
        public static string UserState {
            get {
                return ResourceManager.GetString("UserState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجل ضريبة القيمة المضافة.
        /// </summary>
        public static string VATRegistered {
            get {
                return ResourceManager.GetString("VATRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البائع.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود البائع.
        /// </summary>
        public static string VendorCode {
            get {
                return ResourceManager.GetString("VendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل البائع.
        /// </summary>
        public static string VendorDetails {
            get {
                return ResourceManager.GetString("VendorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات البائع.
        /// </summary>
        public static string VendorInformation {
            get {
                return ResourceManager.GetString("VendorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البائعون.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع البائع.
        /// </summary>
        public static string VendorType {
            get {
                return ResourceManager.GetString("VendorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلن موثق.
        /// </summary>
        public static string VerifiedAdvertiser {
            get {
                return ResourceManager.GetString("VerifiedAdvertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلنون الموثقون.
        /// </summary>
        public static string VerifiedAdvertisers {
            get {
                return ResourceManager.GetString("VerifiedAdvertisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلنون الموثقون والمميزون.
        /// </summary>
        public static string VerifiedAndFeaturedAdvertisers {
            get {
                return ResourceManager.GetString("VerifiedAndFeaturedAdvertisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نطاق الرؤية.
        /// </summary>
        public static string VisibilityScope {
            get {
                return ResourceManager.GetString("VisibilityScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانتظار الموافقة.
        /// </summary>
        public static string Waitingforapproved {
            get {
                return ResourceManager.GetString("Waitingforapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرق السحب.
        /// </summary>
        public static string WithdrawalMethods {
            get {
                return ResourceManager.GetString("WithdrawalMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم، مسجل عقارياً.
        /// </summary>
        public static string YesRealEstateRegistered {
            get {
                return ResourceManager.GetString("YesRealEstateRegistered", resourceCulture);
            }
        }
    }
}
