//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FormResources", typeof(FormResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن نفسي.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الحساب.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجراءات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العنوان.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليقات الادمن.
        /// </summary>
        public static string AdminComments {
            get {
                return ResourceManager.GetString("AdminComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاتفاقية.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف البديل.
        /// </summary>
        public static string AlternativePhoneNumber {
            get {
                return ResourceManager.GetString("AlternativePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ص.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص عربي.
        /// </summary>
        public static string ArabicContent {
            get {
                return ResourceManager.GetString("ArabicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف بالعربية.
        /// </summary>
        public static string ArabicDescription {
            get {
                return ResourceManager.GetString("ArabicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم بالعربية.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر بالعربية.
        /// </summary>
        public static string ArabicShortDescription {
            get {
                return ResourceManager.GetString("ArabicShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالعربي.
        /// </summary>
        public static string ArabicTitle {
            get {
                return ResourceManager.GetString("ArabicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة البانر.
        /// </summary>
        public static string BannerImage {
            get {
                return ResourceManager.GetString("BannerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات اساسية.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيرة الذاتية.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محظور.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهادات.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إكمال الملف الشخصي.
        /// </summary>
        public static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إكمال معلومات ملفك الشخصي لمتابعة استخدام النظام.
        /// </summary>
        public static string CompleteProfileDescription {
            get {
                return ResourceManager.GetString("CompleteProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكمل ملفك الشخصي.
        /// </summary>
        public static string CompleteYourProfile {
            get {
                return ResourceManager.GetString("CompleteYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور الجديدة.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المحتوى.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الغلاف.
        /// </summary>
        public static string CoverPhoto {
            get {
                return ResourceManager.GetString("CoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصص.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محذوف.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب العرض.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدد الترتيب الذي سيظهر به هذا العنصر (1 = الأول).
        /// </summary>
        public static string DisplayOrderHint {
            get {
                return ResourceManager.GetString("DisplayOrderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الحالي: {0} من {1}.
        /// </summary>
        public static string DisplayOrderStatus {
            get {
                return ResourceManager.GetString("DisplayOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلق.
        /// </summary>
        public static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستند.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق من الوثيقة.
        /// </summary>
        public static string Document_Verification {
            get {
                return ResourceManager.GetString("Document Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق من الوثيقة.
        /// </summary>
        public static string DocumentVerification {
            get {
                return ResourceManager.GetString("DocumentVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليم.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني أو اسم المستخدم.
        /// </summary>
        public static string EmailOrUsername {
            get {
                return ResourceManager.GetString("EmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موظف.
        /// </summary>
        public static string Employed {
            get {
                return ResourceManager.GetString("Employed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العمل.
        /// </summary>
        public static string EmploymentStatus {
            get {
                return ResourceManager.GetString("EmploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص انجليزي.
        /// </summary>
        public static string EnglishContent {
            get {
                return ResourceManager.GetString("EnglishContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف بالإنجليزية.
        /// </summary>
        public static string EnglishDescription {
            get {
                return ResourceManager.GetString("EnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالإنجليزية.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر بالإنجليزية.
        /// </summary>
        public static string EnglishShortDescription {
            get {
                return ResourceManager.GetString("EnglishShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالإنجليزي.
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل تأكيد كلمة المرور.
        /// </summary>
        public static string EnterConfirmPassword {
            get {
                return ResourceManager.GetString("EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل البريد الإلكتروني.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كلمة المرور الجديدة.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كلمة المرور القديمة.
        /// </summary>
        public static string EnterOldPassword {
            get {
                return ResourceManager.GetString("EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم هاتفك.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخبرة.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيس بوك.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل الملفات.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنسيق.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الكامل.
        /// </summary>
        public static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالكامل.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرض.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهوايات.
        /// </summary>
        public static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايقونة.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهوية الوطنية أو جواز السفر.
        /// </summary>
        public static string IDorPassport {
            get {
                return ResourceManager.GetString("IDorPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير نشط.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انستجرام.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاهتمامات.
        /// </summary>
        public static string Interests {
            get {
                return ResourceManager.GetString("Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسمى الوظيفي.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكلمات المفتاحية.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغات.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لينكد ان.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الموقع.
        /// </summary>
        public static string LocationInformation {
            get {
                return ResourceManager.GetString("LocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعار.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الاجتماعية.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متزوج.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوسائط.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل الي الأسفل.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل الي الاعلى.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متعدد.
        /// </summary>
        public static string Multiple {
            get {
                return ResourceManager.GetString("Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالعربي.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالانجليزي.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم القومى.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقرب معلم.
        /// </summary>
        public static string NearestLandmark {
            get {
                return ResourceManager.GetString("NearestLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم إضافة {1} في الموقع {0}.
        /// </summary>
        public static string NewEntityOrderInfo {
            get {
                return ResourceManager.GetString("NewEntityOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على مسوقين.
        /// </summary>
        public static string NoMarketersFound {
            get {
                return ResourceManager.GetString("NoMarketersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير ثنائي.
        /// </summary>
        public static string NonBinary {
            get {
                return ResourceManager.GetString("NonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مسوقون مختارون..
        /// </summary>
        public static string NoSelectedMarketers {
            get {
                return ResourceManager.GetString("NoSelectedMarketers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختياري.
        /// </summary>
        public static string optional {
            get {
                return ResourceManager.GetString("optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاختيارات.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الصفحة.
        /// </summary>
        public static string PageType {
            get {
                return ResourceManager.GetString("PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر التصنيف الخاص بهذه الصفحة. لا يمكن تغييره بعد الإنشاء..
        /// </summary>
        public static string PageTypeHint {
            get {
                return ResourceManager.GetString("PageTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات شخصية.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل {0}.
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الملف الشخصي.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم.
        /// </summary>
        public static string PromoCode {
            get {
                return ResourceManager.GetString("PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكواد الخصم.
        /// </summary>
        public static string PromoCodes {
            get {
                return ResourceManager.GetString("PromoCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع كود الخصم.
        /// </summary>
        public static string PromoCodeType {
            get {
                return ResourceManager.GetString("PromoCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبب.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متقاعد.
        /// </summary>
        public static string Retired {
            get {
                return ResourceManager.GetString("Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراجعة.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جارٍ الحفظ.....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف محرك البحث.
        /// </summary>
        public static string SearchEngineDescription {
            get {
                return ResourceManager.GetString("SearchEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامات محرك البحث.
        /// </summary>
        public static string SearchEngineTags {
            get {
                return ResourceManager.GetString("SearchEngineTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان محرك البحث.
        /// </summary>
        public static string SearchEngineTitle {
            get {
                return ResourceManager.GetString("SearchEngineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصطلحات البحث.
        /// </summary>
        public static string SearchTerms {
            get {
                return ResourceManager.GetString("SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار الكل.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المدينة.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الدولة.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار كود الدولة.
        /// </summary>
        public static string SelectCountryCode {
            get {
                return ResourceManager.GetString("SelectCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسوقين المختارين.
        /// </summary>
        public static string SelectedMarketers {
            get {
                return ResourceManager.GetString("SelectedMarketers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع الصفحة.
        /// </summary>
        public static string SelectPageType {
            get {
                return ResourceManager.GetString("SelectPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المحافظة.
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار تيم.
        /// </summary>
        public static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحسين محركات البحث.
        /// </summary>
        public static string SEO {
            get {
                return ResourceManager.GetString("SEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف لتحسين محركات البحث.
        /// </summary>
        public static string SEODescription {
            get {
                return ResourceManager.GetString("SEODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يُستخدم هذا الوصف في وسوم الميتا لمحركات البحث..
        /// </summary>
        public static string SEODescriptionHint {
            get {
                return ResourceManager.GetString("SEODescriptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسوم الميتا الخاصة بـ SEO.
        /// </summary>
        public static string SEOMetaTags {
            get {
                return ResourceManager.GetString("SEOMetaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افصل العلامات بفواصل (مثل: كلمة1، كلمة2).
        /// </summary>
        public static string SEOMetaTagsHint {
            get {
                return ResourceManager.GetString("SEOMetaTagsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان لتحسين محركات البحث.
        /// </summary>
        public static string SEOTitle {
            get {
                return ResourceManager.GetString("SEOTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يُستخدم هذا العنوان لأغراض تحسين محركات البحث ويظهر في نتائج البحث..
        /// </summary>
        public static string SEOTitleHint {
            get {
                return ResourceManager.GetString("SEOTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار المقالات.
        /// </summary>
        public static string ShowArticles {
            get {
                return ResourceManager.GetString("ShowArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار الأطباء.
        /// </summary>
        public static string ShowDoctors {
            get {
                return ResourceManager.GetString("ShowDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض فى الصفحة الرئيسية.
        /// </summary>
        public static string ShowInHomePage {
            get {
                return ResourceManager.GetString("ShowInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار الخدمات.
        /// </summary>
        public static string ShowServices {
            get {
                return ResourceManager.GetString("ShowServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار الأحصائيات.
        /// </summary>
        public static string ShowStatistics {
            get {
                return ResourceManager.GetString("ShowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار شهادات العملاء.
        /// </summary>
        public static string ShowTestimonials {
            get {
                return ResourceManager.GetString("ShowTestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعزب.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهارات.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سناب شات.
        /// </summary>
        public static string Snapchat {
            get {
                return ResourceManager.GetString("Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص بالعربية.
        /// </summary>
        public static string SpecializationAR {
            get {
                return ResourceManager.GetString("SpecializationAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص بالإنجليزية.
        /// </summary>
        public static string SpecializationEN {
            get {
                return ResourceManager.GetString("SpecializationEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الراعي.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت البداية.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طالب.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال التعليقات.
        /// </summary>
        public static string SubmitFeedback {
            get {
                return ResourceManager.GetString("SubmitFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملخص.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوسوم.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فريق.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الفريق.
        /// </summary>
        public static string TeamInformation {
            get {
                return ResourceManager.GetString("TeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تيكتوك.
        /// </summary>
        public static string Tiktok {
            get {
                return ResourceManager.GetString("Tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تويتر.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عاطل عن العمل.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الإستخدامات.
        /// </summary>
        public static string UsageCount {
            get {
                return ResourceManager.GetString("UsageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حد الإستخدام.
        /// </summary>
        public static string UsageLimit {
            get {
                return ResourceManager.GetString("UsageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسماء المستخدمين.
        /// </summary>
        public static string Usernames {
            get {
                return ResourceManager.GetString("Usernames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيم.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الفيديو.
        /// </summary>
        public static string VideoLink {
            get {
                return ResourceManager.GetString("VideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزود الفيديو.
        /// </summary>
        public static string VideoProvider {
            get {
                return ResourceManager.GetString("VideoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الإلكتروني.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واتس اب.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرمل.
        /// </summary>
        public static string Widowed {
            get {
                return ResourceManager.GetString("Widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أُكتب.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالتك.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوتيوب.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
