//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrderResources", typeof(OrderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقبول.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف تعليق.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مخزن.
        /// </summary>
        public static string AddWarehouse {
            get {
                return ResourceManager.GetString("AddWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات المشرف.
        /// </summary>
        public static string AdminNotes {
            get {
                return ResourceManager.GetString("AdminNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع حالات الاسترداد.
        /// </summary>
        public static string AllRefundStatus {
            get {
                return ResourceManager.GetString("AllRefundStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العناصر المعتمدة.
        /// </summary>
        public static string ApprovedItems {
            get {
                return ResourceManager.GetString("ApprovedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد المعلومات.
        /// </summary>
        public static string ApproveInfo {
            get {
                return ResourceManager.GetString("ApproveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد استرداد الأموال.
        /// </summary>
        public static string ApproveRefund {
            get {
                return ResourceManager.GetString("ApproveRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في انتظار التأكيد.
        /// </summary>
        public static string AwaitingConfirmation {
            get {
                return ResourceManager.GetString("AwaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العودة إلى الطلبات.
        /// </summary>
        public static string BackToOrders {
            get {
                return ResourceManager.GetString("BackToOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغى.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغى.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق الاسترداد.
        /// </summary>
        public static string CloseRefund {
            get {
                return ResourceManager.GetString("CloseRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء الطلب.
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتمل.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من إلغاء هذا الطلب؟.
        /// </summary>
        public static string ConfirmCancelOrder {
            get {
                return ResourceManager.GetString("ConfirmCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤكد.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد الطلب.
        /// </summary>
        public static string ConfirmOrder {
            get {
                return ResourceManager.GetString("ConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم.
        /// </summary>
        public static string CouponCode {
            get {
                return ResourceManager.GetString("CouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الحالية.
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني للعميل.
        /// </summary>
        public static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العميل.
        /// </summary>
        public static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العميل.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسليم.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسليم.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل المخزن.
        /// </summary>
        public static string EditWarehouse {
            get {
                return ResourceManager.GetString("EditWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم التتبع.
        /// </summary>
        public static string EnterTrackingNumber {
            get {
                return ResourceManager.GetString("EnterTrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ المتوقع للتسليم.
        /// </summary>
        public static string ExpectedDelivery {
            get {
                return ResourceManager.GetString("ExpectedDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجاني.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اعتماد المعلومات.
        /// </summary>
        public static string InfoApproved {
            get {
                return ResourceManager.GetString("InfoApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد التنفيذ.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الفحص.
        /// </summary>
        public static string Inspecting {
            get {
                return ResourceManager.GetString("Inspecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فحص المنتج.
        /// </summary>
        public static string InspectingItem {
            get {
                return ResourceManager.GetString("InspectingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد النقل.
        /// </summary>
        public static string InTransit {
            get {
                return ResourceManager.GetString("InTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ الاسترداد غير صالح.
        /// </summary>
        public static string InvalidRefundAmount {
            get {
                return ResourceManager.GetString("InvalidRefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال الحالة غير صحيح.
        /// </summary>
        public static string InvalidStatusTransition {
            get {
                return ResourceManager.GetString("InvalidStatusTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استلام المنتج.
        /// </summary>
        public static string ItemReceived {
            get {
                return ResourceManager.GetString("ItemReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العناصر.
        /// </summary>
        public static string ItemsCount {
            get {
                return ResourceManager.GetString("ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم شحن المنتج مجددًا.
        /// </summary>
        public static string ItemShippedBack {
            get {
                return ResourceManager.GetString("ItemShippedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العناصر.
        /// </summary>
        public static string ItemsCount {
            get {
                return ResourceManager.GetString("ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد كمُسلّم.
        /// </summary>
        public static string MarkAsDelivered {
            get {
                return ResourceManager.GetString("MarkAsDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع علامة &quot;مستلم&quot;.
        /// </summary>
        public static string MarkAsReceived {
            get {
                return ResourceManager.GetString("MarkAsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع علامة &quot;تم الشحن&quot;.
        /// </summary>
        public static string MarkAsShipped {
            get {
                return ResourceManager.GetString("MarkAsShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل إلى المعالجة.
        /// </summary>
        public static string MoveToProcessing {
            get {
                return ResourceManager.GetString("MoveToProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الانتقال إلى الشحن.
        /// </summary>
        public static string MoveToShipping {
            get {
                return ResourceManager.GetString("MoveToShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يُحتاج إلى مزيد من المعلومات.
        /// </summary>
        public static string NeedMoreInfo {
            get {
                return ResourceManager.GetString("NeedMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة التالية.
        /// </summary>
        public static string NextStatus {
            get {
                return ResourceManager.GetString("NextStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد منتجات.
        /// </summary>
        public static string NoProducts {
            get {
                return ResourceManager.GetString("NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد منتجات في هذا الطلب.
        /// </summary>
        public static string NoProductsInOrder {
            get {
                return ResourceManager.GetString("NoProductsInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد شحنات.
        /// </summary>
        public static string NoShipments {
            get {
                return ResourceManager.GetString("NoShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إنشاء شحنات لهذا الطلب بعد.
        /// </summary>
        public static string NoShipmentsYet {
            get {
                return ResourceManager.GetString("NoShipmentsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الطريق.
        /// </summary>
        public static string OnTheWay {
            get {
                return ResourceManager.GetString("OnTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفتوح.
        /// </summary>
        public static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إكمال الطلب.
        /// </summary>
        public static string OrderCompleted {
            get {
                return ResourceManager.GetString("OrderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحكم في الطلب.
        /// </summary>
        public static string OrderControl {
            get {
                return ResourceManager.GetString("OrderControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الطلب.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناصر الطلب.
        /// </summary>
        public static string OrderItems {
            get {
                return ResourceManager.GetString("OrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تأكيد الطلب أولاً.
        /// </summary>
        public static string OrderMustBeConfirmed {
            get {
                return ResourceManager.GetString("OrderMustBeConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون الطلب في حالة قيد الانتظار.
        /// </summary>
        public static string OrderMustBePending {
            get {
                return ResourceManager.GetString("OrderMustBePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون الطلب قيد المعالجة.
        /// </summary>
        public static string OrderMustBeProcessing {
            get {
                return ResourceManager.GetString("OrderMustBeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب شحن الطلب أولاً.
        /// </summary>
        public static string OrderMustBeShipped {
            get {
                return ResourceManager.GetString("OrderMustBeShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقدم الطلب.
        /// </summary>
        public static string OrderProgress {
            get {
                return ResourceManager.GetString("OrderProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفض الطلب.
        /// </summary>
        public static string OrderRejected {
            get {
                return ResourceManager.GetString("OrderRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الطلب.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملخص الطلب.
        /// </summary>
        public static string OrderSummary {
            get {
                return ResourceManager.GetString("OrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرج للتسليم.
        /// </summary>
        public static string OutForDelivery {
            get {
                return ResourceManager.GetString("OutForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدفوع.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدفوع جزئياً.
        /// </summary>
        public static string PartiallyPaid {
            get {
                return ResourceManager.GetString("PartiallyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسترجع جزئياً.
        /// </summary>
        public static string PartiallyRefunded {
            get {
                return ResourceManager.GetString("PartiallyRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الدفع.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الدفع.
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الدفع.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة الدفع.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الدفع.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري المعالجة.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معالجة استرداد الأموال.
        /// </summary>
        public static string ProcessRefund {
            get {
                return ResourceManager.GetString("ProcessRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستلم.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ الاسترجاع.
        /// </summary>
        public static string RefundAmount {
            get {
                return ResourceManager.GetString("RefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الموافقة على الاسترجاع.
        /// </summary>
        public static string RefundApproved {
            get {
                return ResourceManager.GetString("RefundApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إغلاق الاسترداد بنجاح.
        /// </summary>
        public static string RefundClosedSuccessfully {
            get {
                return ResourceManager.GetString("RefundClosedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتمل استرداد الأموال.
        /// </summary>
        public static string RefundCompleted {
            get {
                return ResourceManager.GetString("RefundCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الاسترداد.
        /// </summary>
        public static string RefundDetails {
            get {
                return ResourceManager.GetString("RefundDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسترجع.
        /// </summary>
        public static string Refunded {
            get {
                return ResourceManager.GetString("Refunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الاسترداد.
        /// </summary>
        public static string RefundInformation {
            get {
                return ResourceManager.GetString("RefundInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الاسترداد.
        /// </summary>
        public static string RefundNumber {
            get {
                return ResourceManager.GetString("RefundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب الاسترداد.
        /// </summary>
        public static string RefundReason {
            get {
                return ResourceManager.GetString("RefundReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفض الاسترجاع.
        /// </summary>
        public static string RefundRejected {
            get {
                return ResourceManager.GetString("RefundRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب استرجاع.
        /// </summary>
        public static string RefundRequest {
            get {
                return ResourceManager.GetString("RefundRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم طلب الاسترجاع.
        /// </summary>
        public static string RefundRequested {
            get {
                return ResourceManager.GetString("RefundRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استلام طلب الاسترداد.
        /// </summary>
        public static string RefundRequestReceived {
            get {
                return ResourceManager.GetString("RefundRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسترجاعات.
        /// </summary>
        public static string Refunds {
            get {
                return ResourceManager.GetString("Refunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الاسترجاع.
        /// </summary>
        public static string RefundStatus {
            get {
                return ResourceManager.GetString("RefundStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استرداد الأموال بنجاح.
        /// </summary>
        public static string RefundSuccessful {
            get {
                return ResourceManager.GetString("RefundSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سير عمل استرداد الأموال.
        /// </summary>
        public static string RefundWorkflow {
            get {
                return ResourceManager.GetString("RefundWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفض بعد الفحص.
        /// </summary>
        public static string RejectAfterInspection {
            get {
                return ResourceManager.GetString("RejectAfterInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب الرفض.
        /// </summary>
        public static string RejectionReason {
            get {
                return ResourceManager.GetString("RejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string RequestedDate {
            get {
                return ResourceManager.GetString("RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العناصر المطلوبة.
        /// </summary>
        public static string RequestedItems {
            get {
                return ResourceManager.GetString("RequestedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب مزيد من المعلومات.
        /// </summary>
        public static string RequestMoreInfo {
            get {
                return ResourceManager.GetString("RequestMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتجع.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكلفة شحن الإرجاع.
        /// </summary>
        public static string ReturnShippingCost {
            get {
                return ResourceManager.GetString("ReturnShippingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد مراجعة الطلب.
        /// </summary>
        public static string ReviewingRequest {
            get {
                return ResourceManager.GetString("ReviewingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى اختيار تاريخ تسليم صالح.
        /// </summary>
        public static string SelectValidDeliveryDate {
            get {
                return ResourceManager.GetString("SelectValidDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر البائع.
        /// </summary>
        public static string SelectVendor {
            get {
                return ResourceManager.GetString("SelectVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشحنات.
        /// </summary>
        public static string Shipments {
            get {
                return ResourceManager.GetString("Shipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الشحنة.
        /// </summary>
        public static string ShipmentTotal {
            get {
                return ResourceManager.GetString("ShipmentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الشحن.
        /// </summary>
        public static string Shipped {
            get {
                return ResourceManager.GetString("Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشحن.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكلفة الشحن.
        /// </summary>
        public static string ShippingCost {
            get {
                return ResourceManager.GetString("ShippingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الشحن.
        /// </summary>
        public static string ShippingInformation {
            get {
                return ResourceManager.GetString("ShippingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدء المعالجة.
        /// </summary>
        public static string StartProcessing {
            get {
                return ResourceManager.GetString("StartProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدء المراجعة.
        /// </summary>
        public static string StartReview {
            get {
                return ResourceManager.GetString("StartReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير حالة الطلب بنجاح.
        /// </summary>
        public static string StatusChangedSuccessfully {
            get {
                return ResourceManager.GetString("StatusChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع الفرعي.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضريبة.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الإجمالي.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التتبع.
        /// </summary>
        public static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التتبع مطلوب.
        /// </summary>
        public static string TrackingNumberRequired {
            get {
                return ResourceManager.GetString("TrackingNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة.
        /// </summary>
        public static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المعاملة مطلوب.
        /// </summary>
        public static string TransactionIdRequired {
            get {
                return ResourceManager.GetString("TransactionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البائع.
        /// </summary>
        public static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العملية.
        /// </summary>
        public static string TransactionID {
            get {
                return ResourceManager.GetString("TransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض السجل.
        /// </summary>
        public static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في انتظار الإرجاع.
        /// </summary>
        public static string WaitingForReturn {
            get {
                return ResourceManager.GetString("WaitingForReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المخازن.
        /// </summary>
        public static string WarehouseManagement {
            get {
                return ResourceManager.GetString("WarehouseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخازن.
        /// </summary>
        public static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
    }
}
